name: publish

on:
  workflow_dispatch:

  push:
    branches: 
      - 'main'
    tags: 
      - 'v*'

  pull_request:
    branches: 
      - 'main'

env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Enable GitHub Packages Source
        run: dotnet nuget enable source GitHub_FlederM4us

      - name: Restore
        run: dotnet restore
        env:
          GH_NUGET_AUTH_TOKEN: ${{ secrets.GH_NUGET_AUTH_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
